# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: RuBees docs

# Short description (goes below the title; it will also be used in the RSS feed)
# description: RuBees Docs

# Your name, as you want it to appear underneath each post and in the footer
# author: Arne Brasseur, RuBees

# Your email if you want it to be linked on the contact page
# author_email: you@example.com

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: kramdown

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
# paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
# exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

kramdown:
  input: GFM
  parse_block_html: true
